// Electron strips PATH down to /usr/bin:/bin:/usr/sbin:/sbin.
// Homebrew lives in /opt/homebrew/bin (Apple Silicon) or /usr/local/bin (Intel).
// Fix this before any child_process calls (sox `rec`, `say`) happen.
if (process.platform === 'darwin') {
  const brewBin = process.arch === 'arm64' ? '/opt/homebrew/bin' : '/usr/local/bin';
  if (!(process.env.PATH ?? '').includes(brewBin)) {
    process.env.PATH = `${brewBin}:/usr/local/bin:${process.env.PATH ?? ''}`;
  }
}

import { app, BrowserWindow, ipcMain, systemPreferences, globalShortcut } from 'electron';
import path from 'path';
import { AudioRecorder } from '../src/audio/recorder';
import { createSpeaker } from '../src/audio/createSpeaker';
import { getVoiceInfo } from '../src/audio/voiceInfo';
import { startTtsServerIfNeeded, stopTtsServer } from '../src/audio/ttsServerManager';
import { Transcriber } from '../src/stt/transcriber';
import { TARSClient } from '../src/llm/client';
import { config } from '../src/config';
import type { ProgressInfo } from '../src/stt/transcriber';

type AppState = 'idle' | 'recording' | 'transcribing' | 'thinking' | 'speaking' | 'error';

let win: BrowserWindow | null = null;
let appState: AppState = 'idle';
let ttsEnabled = config.tts.enabled;

const recorder = new AudioRecorder();
const speaker = createSpeaker();
const transcriber = new Transcriber();
const tarsClient = new TARSClient();

tarsClient.onSearch = (query: string) => {
  sysMsg(`ACCESSING EXTERNAL DATA FEEDS: ${query}`);
};

speaker.onSpectrum = (bands) => {
  send('telemetry-spectrum', bands);
};

// ── IPC helpers ───────────────────────────────────────────────────────────────

function send(channel: string, data?: unknown): void {
  win?.webContents.send(channel, data);
}

function setState(s: AppState): void {
  appState = s;
  send('state-change', { state: s });
}

function sysMsg(text: string): void {
  send('system-message', { text });
}

// ── Voice info (analytics VOICE panel) ────────────────────────────────────────
//
// getVoiceInfo() is also checked once synchronously in get-config below (for
// the very first paint), but the Qwen server can still be mid-load at that
// exact moment -- MLX model loading can take many seconds, especially on a
// cold cache -- so that one-shot check can catch it as "unreachable" and the
// UI would just show that stale label for the rest of the session even once
// the server finishes loading and real speech works fine. This retries with
// backoff until it actually resolves, pushing corrections to the renderer.

async function refreshVoiceInfoUntilReady(): Promise<void> {
  for (let i = 0; i < 30; i++) {
    const info = await getVoiceInfo();
    send('voice-info', info);
    if (!info.voice.startsWith('UNREACHABLE')) return;
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }
}

// ── Oracle (Tarot / I Ching / Art of War / Meditations sidebar panel) ─────────
// Purely cosmetic flavor content, generated by the same local model as chat --
// refreshes on a timer rather than per-turn or per-search, since it's a second
// call to a model that can typically only run one inference at a time; tying
// it to every response would compete with (and slow down) the actual chat.

const ORACLE_REFRESH_MS = 5 * 60 * 1000;
let oracleIntervalStarted = false;

// Both the Oracle refresh and the idle prompt below are background calls to
// the same local model, outside of a normal user turn -- appState alone
// doesn't protect them from each other: generateOracleReading() doesn't (and
// shouldn't) flip appState away from 'idle' while it's in flight, since it's
// not a user-facing "TARS is thinking" moment. Without this flag, the idle
// timer could see appState still 'idle' mid-Oracle-refresh and fire a second,
// concurrent request at the same model.
let backgroundLlmBusy = false;

async function refreshOracle(): Promise<void> {
  // Skip a cycle rather than queue behind an in-flight chat turn (or idle
  // prompt) -- the next timer tick will just try again.
  if (appState !== 'idle' || backgroundLlmBusy) return;
  backgroundLlmBusy = true;
  try {
    const reading = await tarsClient.generateOracleReading();
    send('oracle-reading', reading);
  } catch (err) {
    console.warn('[oracle] generation failed:', err instanceof Error ? err.message : err);
  } finally {
    backgroundLlmBusy = false;
  }
}

// ── Whisper setup ─────────────────────────────────────────────────────────────

function initWhisper(): void {
  if (!config.whisper.enabled) {
    send('whisper-status', { status: 'disabled' });
    sysMsg('Voice input DISABLED (WHISPER_ENABLED=false). Press [ENTER] to type.');
    return;
  }

  sysMsg(`WHISPER: Loading ${config.whisper.model} — voice available when ready.`);

  transcriber.onProgress = (info: ProgressInfo) => {
    send('whisper-progress', info);
    if (info.status === 'ready') {
      sysMsg('WHISPER READY — press [SPACE] to transmit voice.');
    } else if (info.status === 'error') {
      sysMsg(`WHISPER ERROR: ${info.error?.message ?? 'unknown'}`);
    }
  };

  transcriber.loadModel();
}

// ── Voice pipeline ────────────────────────────────────────────────────────────

// Shared by both a real user turn and a proactive idle prompt below -- same
// token-forwarding, TTS-parallel-with-typing, and error-handling logic either
// way, just a different async generator feeding it.
async function runTurn(gen: AsyncGenerator<string>): Promise<void> {
  setState('thinking');

  try {
    let speakPromise: Promise<void> = Promise.resolve();

    // Fires as soon as the full response is known (before it's typed out),
    // so speech starts in parallel with the typing animation instead of after it.
    tarsClient.onResponseReady = (fullText) => {
      if (!fullText.trim()) return;
      setState('speaking');
      if (ttsEnabled) speakPromise = speaker.speak(fullText);
    };

    for await (const token of gen) {
      send('token', { text: token });
    }

    await speakPromise;

    send('response-complete', {
      stats: tarsClient.lastStats,
      turns: tarsClient.turnCount,
    });

    setState('idle');
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    sysMsg(`ERROR: ${msg}`);
    setState('error');
    setTimeout(() => { if (appState === 'error') setState('idle'); }, 5000);
  }
}

async function processInput(text: string): Promise<void> {
  send('user-message', { text });
  await runTurn(tarsClient.chat(text));
}

// ── Idle prompt (breaks a long silence with trivia or a fun question) ────────
// No 'user-message' is sent for this -- TARS is volunteering it, not
// responding to something the user said, so no "YOU" bubble should appear.

const IDLE_CHECK_INTERVAL_MS = 30_000;
const IDLE_MIN_MS = 5 * 60 * 1000;
const IDLE_MAX_MS = 10 * 60 * 1000;

function randomIdleThreshold(): number {
  return IDLE_MIN_MS + Math.random() * (IDLE_MAX_MS - IDLE_MIN_MS);
}

let idleThresholdMs = randomIdleThreshold();

function startIdleWatch(): void {
  setInterval(() => {
    if (!config.idlePrompt.enabled) return;
    // backgroundLlmBusy also covers an in-flight Oracle refresh -- appState
    // alone wouldn't catch that, since Oracle generation deliberately doesn't
    // touch appState (it's not a user-facing "thinking" moment).
    if (appState !== 'idle' || backgroundLlmBusy) return;
    if (tarsClient.msSinceLastActivity() < idleThresholdMs) return;

    idleThresholdMs = randomIdleThreshold(); // reroll before firing, not after
    backgroundLlmBusy = true;
    void runTurn(tarsClient.idlePrompt()).finally(() => { backgroundLlmBusy = false; });
  }, IDLE_CHECK_INTERVAL_MS);
}

// ── IPC handlers ──────────────────────────────────────────────────────────────

ipcMain.on('start-recording', () => {
  if (appState !== 'idle' || !transcriber.isReady) return;
  setState('recording');
  recorder.start();
});

ipcMain.on('stop-recording', () => {
  if (appState !== 'recording') return;
  setState('transcribing');

  void (async () => {
    try {
      const audioPath = await recorder.stop();
      let text: string;

      try {
        text = await transcriber.transcribe(audioPath);
      } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        if (msg === 'AUDIO_TOO_SHORT') {
          sysMsg('Audio too short — nothing recorded.');
          setState('idle');
          return;
        }
        throw err;
      }

      if (!text) {
        sysMsg('No speech detected.');
        setState('idle');
        return;
      }

      await processInput(text);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      sysMsg(`RECORDING ERROR: ${msg}`);
      setState('error');
      setTimeout(() => { if (appState === 'error') setState('idle'); }, 5000);
    }
  })();
});

ipcMain.on('send-message', (_event, text: string) => {
  if (!['idle', 'error'].includes(appState)) return;
  void processInput(text);
});

ipcMain.on('clear-history', () => {
  tarsClient.clearHistory();
  sysMsg('Mission log cleared. Conversation history reset.');
});

ipcMain.on('toggle-tts', () => {
  ttsEnabled = !ttsEnabled;
  sysMsg(`TTS ${ttsEnabled ? 'ENABLED' : 'DISABLED'}`);
  send('tts-state', { enabled: ttsEnabled });
});

ipcMain.on('stop-tts', () => {
  speaker.stop();
  if (appState === 'speaking') setState('idle');
});

ipcMain.on('quit', () => app.quit());

ipcMain.handle('get-config', async () => {
  const voice = await getVoiceInfo();
  return {
    humor: config.tars.humor,
    honesty: config.tars.honesty,
    lmStudioUrl: config.lmStudio.baseURL,
    chatModel: config.lmStudio.chatModel,
    whisperModel: config.whisper.model,
    whisperEnabled: config.whisper.enabled,
    ttsEnabled,
    ttsVoice: config.tts.voice,
    voiceEngine: voice.engine,
    voiceLabel: voice.voice,
  };
});

// ── Window creation ───────────────────────────────────────────────────────────

async function createWindow(): Promise<void> {
  // Request microphone access — fire-and-forget so the dialog doesn't block
  // the window from opening. The IPC handler for start-recording checks
  // isReady, so recording won't start until permission is resolved anyway.
  if (process.platform === 'darwin') {
    systemPreferences.askForMediaAccess('microphone').then((granted) => {
      if (!granted) sysMsg('WARNING: Microphone access denied — voice input unavailable.');
    }).catch(() => {});
  }

  win = new BrowserWindow({
    width: 1024,
    height: 700,
    minWidth: 800,
    minHeight: 540,
    backgroundColor: '#001200',
    titleBarStyle: 'hiddenInset',
    trafficLightPosition: { x: 14, y: 14 },
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  win.on('closed', () => { win = null; });

  // Register did-finish-load BEFORE loadFile() — loadFile() resolves its
  // Promise by internally waiting for this same event, so registering after
  // the await means we always miss it.
  win.webContents.on('did-finish-load', () => {
    sysMsg('SYSTEM ONLINE. Link: ' + config.lmStudio.baseURL);
    sysMsg(
      `HUMOR ${config.tars.humor}%  HONESTY ${config.tars.honesty}%  COOPERATION 100%`
    );
    initWhisper();
    void refreshVoiceInfoUntilReady();

    void refreshOracle();
    if (!oracleIntervalStarted) {
      oracleIntervalStarted = true;
      setInterval(() => { void refreshOracle(); }, ORACLE_REFRESH_MS);
    }
  });

  win.loadFile(
    path.join(__dirname, '../../electron/renderer/index.html')
  ).catch(() => {});

  // DevTools toggle — always available via Cmd+Shift+I or F12
  globalShortcut.register('CommandOrControl+Shift+I', () => {
    win?.webContents.toggleDevTools();
  });
  globalShortcut.register('F12', () => {
    win?.webContents.toggleDevTools();
  });
}

// Fire-and-forget -- kicked off as early as possible so the Python model load
// overlaps with the rest of Electron's startup instead of adding to it. The
// existing QwenSpeaker fallback (see createSpeaker.ts) already handles "not
// ready yet" by falling back to the say voice, so nothing needs to block on it.
void startTtsServerIfNeeded();

startIdleWatch();

app.whenReady().then(createWindow);

app.on('will-quit', () => {
  globalShortcut.unregisterAll();
  speaker.stop();
  stopTtsServer();
});

app.on('window-all-closed', () => app.quit());

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) void createWindow();
});
